image: osul/centos7-ruby:2.3

before_script:
  - gem install bundler
  - touch log/application.log
  - touch log/test.log
  - bundle install --jobs $(nproc) --path=/cache/bundler

  # The above commands will remove the instance directories.
  # Gitlab needs them to exist before the runner can use them.
  - mkdir -p /cache/solr-test
  - mkdir -p /cache/fcrepo4-test-data

  # Set up environment
  - bundle exec rake db:create RAILS_ENV=test
  - RAILS_ENV=test bundle exec rake db:reset

rspec:
  script:
    - xvfb-run -a bundle exec rake spec_ci
