image: osul/centos7-ruby:2.3

before_script:
  - gem install bundler
  - touch log/application.log
  - touch log/test.log
  - bundle install --jobs $(nproc) --path=/cache/bundler

  # Copy CI test YAMLs
  - cp -f /fcrepo_wrapper_test.yml config/fcrepo_wrapper_test.yml
  - cp -f /solr_wrapper_test.yml config/solr_wrapper_test.yml

  # Set up environment
  - bundle exec rake db:create RAILS_ENV=test
  - RAILS_ENV=test bundle exec rake db:reset

rspec:
  script:
    - xvfb-run -a bundle exec rake spec
