image: osul/centos7-ruby:2.3

before_script:
  - gem install bundler
  - touch log/application.log
  - touch log/test.log
  - bundle install --jobs $(nproc) --path=/cache/bundler
  - cp config/handle_server.yml.sample config/handle_server.yml
  - cp config/local_env.yml.sample config/local_env.yml

  - if [ ! -d /cache/hsj-8.1.1/ ]; then git clone git@code.osu.edu:osul-ads/hsj-8.1.1.git /cache/hsj-8.1.1; fi

  # remove the instance directories every time we test
  - rm -rf /cache/solr-test/*
  - rm -rf /cache/fcrepo4-test-data/*

  # Gitlab needs them to exist before the runner can use them.
  - mkdir -p /cache/solr-test
  - mkdir -p /cache/fcrepo4-test-data

  # Set up environment
  - bundle exec rake db:create RAILS_ENV=test
  - RAILS_ENV=test bundle exec rake db:reset

rspec:
  script:
    - xvfb-run -a bundle exec rake spec_ci
