image: osul/centos6-ruby:2.3

before_script:
  # Configure SSH deployment key inside docker image
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  # Try installing Java
  - 'which java || ( wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.rpm" && rpm -ivh jdk-8u45-linux-x64.rpm )'

  # Install dependencies
  - ruby -v
  - which ruby
  - bundle install --jobs $(nproc) "${FLAGS[@]}"

  # Set up environment
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare

rspec:
  script:
    - xvfb-run -a bundle exec rake spec
