image: osul/centos7-ruby:2.3

variables:
  SOLR_CORE_NAME: "dcs-test"
  SOLR_CONFIG_DIR: "solr/config"
  SOLR_URL: "http://osul__solr:8983/solr/dcs-test"
  FEDORA_URL: "http://osul__fedora:8080/fcrepo/rest"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  HDL_HOME: "vendor/hsj/8.1.1"
  HDL_KEY: "vendor/hsj/8.1.1/admpriv.bin"
  HDL_PREFIX: "1811.1"
  HDL_MINT: "true"

cache:
  paths:
  - vendor/hsj/
  - vendor/bundle/

before_script:
  # Configure SSH deployment key inside docker image
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  # Setup the environment
  - bundle install --deployment --jobs $(nproc)
  - if [ ! -d vendor/hsj/8.1.1/ ]; then git clone git@code.osu.edu:osul-ads/hsj-8.1.1.git vendor/hsj/8.1.1; fi
  - mkdir ~/.handle
  - echo "140.254.87.133 10.0.0.168" > ~/.handle/local_addresses
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare

rspec:
  services:
    - redis
    - osul/fedora:4.5.1
    - osul/solr:6.1
  script:
    - xvfb-run -a bundle exec rake spec

rubocop:
  before_script:
    - bundle install --deployment --jobs $(nproc)
  script:
    - bundle exec rubocop
