require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the -D/--display-cop-names
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: false
  # Exclude some GitLab files
  Exclude:
    - 'vendor/**/*'
    - 'db/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'solr/**/*'
    - 'log/*'

##################### Style ##################################

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Alias:
  Enabled: false

#################### Metrics ################################

Metrics/AbcSize:
  Enabled: true
  Max: 60

Metrics/MethodLength:
  Enabled: true
  Max: 40

Metrics/ClassLength:
  Enabled: true
  Max: 300

##################### Rails ##################################

# Enables Rails cops.
Rails:
  Enabled: true

##################### RSpec ##################################

RSpec/ExampleLength:
  Enabled: true
  Max: 10
