default: &default
  mint: <%= ENV['HDL_MINT'] == "true" ? true : false %>
  index: <%= ENV['HDL_INDEX'] || 300 %>
  admin_passphrase: <%= ENV['HDL_PASS'] || "" %>
  url: <%= ENV['HDL_URL'] || "http://localhost:3000/concern/generic_works/" %>

development:
  <<: *default
  prefix: <%= ENV['HDL_PREFIX'] || "1234.DEV" %>
  admin_handle: <%= ENV['HDL_ADMIN'] || "1234.TEST/ADMIN" %>
  admin_priv_key: <%= ENV['HDL_KEY'] || "spec/support/hdl/admpriv.bin" %>

test:
  <<: *default
  mint: true
  prefix: <%= ENV['HDL_PREFIX'] || "1234.TEST" %>
  admin_handle: <%= ENV['HDL_ADMIN'] || "1234.TEST/ADMIN" %>
  admin_priv_key: <%= ENV['HDL_KEY'] || "spec/support/hdl/admpriv.bin" %>

production:
  <<: *default
  prefix: <%= ENV['HDL_PREFIX'] || "1234" %>
  admin_handle: <%= ENV['HDL_ADMIN'] || "0.NA/1234" %>
  admin_priv_key: <%= ENV['HDL_KEY'] || "tmp/hdl/admpriv.bin" %>
