# Generated by curation_concerns:models:install
class FileSet < ActiveFedora::Base
  include ::CurationConcerns::FileSetBehavior
  include Sufia::FileSetBehavior

  # Eventually will have to be moved to presenter / and solrdocument for speedier results
  def loris_id
    ActiveFedora::Noid.treeify(original_file.id) + '-' + original_file.versions.last.label
  end
end
