# Generated by curation_concerns:models:install
class FileSet < ActiveFedora::Base
  include ::CurationConcerns::FileSetBehavior
  include Sufia::FileSetBehavior
  include ManagedByUnit
  include Iiifable

  self.indexer = FileSetIndexer

  def under_copyright?
    if parent.respond_to? :under_copyright?
      parent.under_copyright?
    else
      true
    end
  end

  # Override image mime types to include 'application/octet-stream'
  def self.image_mime_types
    super << 'application/octet-stream'
  end

  def to_solr
    super.merge!(original_file_id_ss: original_file_id, original_file_version_ss: original_file_version)
  end

  delegate :id, to: :original_file, prefix: true, allow_nil: true

  def original_file_version
    original_file.versions.last.label if original_file&.versions&.any?
  end

  private

  def set_admin_policy
    self.unit = parent&.unit if parent.present?
    super
  end
end

GenericWork.all.each do |e|
  unless e.representative_id.nil?
    pdf = FileSet.find e.representative_id
    puts "\"#{e.title[0]}\",#{pdf.label}";
  else
      puts "\"#{e.title[0]}\""
  end
end
